### PR TITLE
Fixing RHEL 6 and 7 not having repoquery -y

### LINKED ISSUE #641: 'repoquery -y' fails on EL6 and EL7
### Scripted installer fails
```
curl -sSL https://stackstorm.com/packages/install.sh | bash -s --   --unstable --version=3.1dev   --user=st2admin --password=Ch@ngeMe
```

### Error log
```
20200421T185906+0000 Generating yum cache for StackStorm_unstable...
20200421T185910+0000 Importing GPG key 0x1D66E01F:
20200421T185910+0000  Userid: "https://packagecloud.io/StackStorm/unstable (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
20200421T185910+0000  From  : https://packagecloud.io/StackStorm/unstable/gpgkey
20200421T190005+0000 Generating yum cache for StackStorm_unstable-source...
20200421T190011+0000 
20200421T190011+0000 The repository is setup! You can now install packages.
20200421T190011+0000 Usage: repoquery [options]
20200421T190011+0000 
20200421T190011+0000 repoquery: error: no such option: -y
20200421T190011+0000 Could not find requested version of st2!!!
20200421T190011+0000 Usage: repoquery [options]
20200421T190011+0000 
20200421T190011+0000 repoquery: error: no such option: -y
20200421T190011+0000 ############### ERROR ###############
20200421T190011+0000 # Failed on Get package versions #
20200421T190011+0000 #####################################
```

Looks like a regression from https://github.com/StackStorm/st2-packages/pull/639 when `repoquery -y` was added.

`-y` flag is non-existent on `EL6`.

### PR DESCRIPTION
**Pull request by nmaludy**
Closes #641 

Moves the `RHMAJVER` test to the top of the function.

Based on the `RHMAJVER` it adds in the `-y` flag for `repoquery`

Also fixed a bug in the Mistral test where we were using `&&` inside of single brackets instead of `-a` for logical AND.

**Testing steps - CentOS 7**
(assumes fresh CentOS 7 VM)
```bash
$ sudo yum -y install wget
$ wget https://raw.githubusercontent.com/nmaludy/st2-packages/bugfix/rhel-6-7-repoquery/scripts/st2bootstrap-el7.sh
$ chmod a+x ./st2bootstrap-el7.sh
$ sudo bash st2bootstrap-el7.sh --version=3.1dev --unstable   --user=st2admin --password=Ch@ngeMe
```

**Testing steps - CentOS 8**
(assumes fresh CentOS 8 VM)
```bash
$ sudo yum -y install wget
$ wget https://raw.githubusercontent.com/nmaludy/st2-packages/bugfix/rhel-6-7-repoquery/scripts/st2bootstrap-el8.sh
$ chmod a+x ./st2bootstrap-el8.sh
$ sudo bash st2bootstrap-el8.sh --version=3.2dev --unstable   --user=st2admin --password=Ch@ngeMe
```

### CODE REVIEW

File: scripts/includes/rhel.sh [hunk 1]
```diff
@@ -9,35 +9,42 @@ install_yum_utils() {
...
-      sudo repoquery -y --nvr --show-duplicates st2
+      sudo repoquery ${REPOQUERY_FLAGS} st2
       exit 3
     fi
     ST2_PKG=${ST2_VER}
 
-    local RHMAJVER=`cat /etc/redhat-release | sed 's/[^0-9.]*\([0-9.]\).*/\1/'`
-    local ST2MISTRAL_VER=$(repoquery -y --nvr --show-duplicates st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
-    if [ -z "$ST2MISTRAL_VER" && "$RHMAJVER" != '8' ]; then
+    local ST2MISTRAL_VER=$(repoquery ${REPOQUERY_FLAGS} st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
```
Comment (punkrokk) [inline scripts/includes/rhel.sh:27]: same here... and a few other places

File: scripts/includes/rhel.sh [hunk 2]
```diff
@@ -9,35 +9,42 @@ install_yum_utils() {
 get_full_pkg_versions() {
   if [ "$VERSION" != '' ];
   then
-    local ST2_VER=$(repoquery -y --nvr --show-duplicates st2 | grep -F st2-${VERSION} | sort --version-sort | tail -n 1)
+    local RHMAJVER=`cat /etc/redhat-release | sed 's/[^0-9.]*\([0-9.]\).*/\1/'`
+    local REPOQUERY_FLAGS="--nvr --show-duplicates"
+    if [ "$RHMAJVER" -ge "8" ]; then
+      # RHEL 8 and newer, you need "-y" flag to avoid being prompted to confirm "yes"
+      local REPOQUERY_FLAGS="-y ${REPOQUERY_FLAGS}"
```
Comment (punkrokk) [inline scripts/includes/rhel.sh:16]: So what if instead of bundling all the args together... you did something like:
if el8 then:
`DASH_YES="-y"`
else
`DASH_YES=""
fi

This would retain the flags in place and help the next reader better understand what's going on, and be a less complex change.

Comment (armab) [reply scripts/includes/rhel.sh:16]: I agree with approach that `VAR="-y"` would look more readable and straightforward :+1: 

---

Personally I would remove this part from templating alltogether to have a dedicated block for each platform as it became too spammy. It's not normal when EL6 and EL7 bash file include EL8 checks.

File: scripts/includes/rhel.sh [hunk 3]
```diff
@@ -9,35 +9,42 @@ install_yum_utils() {
...
 
-    local RHMAJVER=`cat /etc/redhat-release | sed 's/[^0-9.]*\([0-9.]\).*/\1/'`
-    local ST2MISTRAL_VER=$(repoquery -y --nvr --show-duplicates st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
-    if [ -z "$ST2MISTRAL_VER" && "$RHMAJVER" != '8' ]; then
+    local ST2MISTRAL_VER=$(repoquery ${YES_FLAG} --nvr --show-duplicates st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
+    # RHEL 8 and newer does not install Mistral
+    if [ -z "$ST2MISTRAL_VER" -a "$RHMAJVER" -lt "8" ]; then
       echo "Could not find requested version of st2mistral!!!"
-      sudo repoquery -y --nvr --show-duplicates st2mistral
+      sudo repoquery ${YES_FLAG} --nvr --show-duplicates st2mistral
```
Comment (armab) [inline scripts/includes/rhel.sh:31]:
```suggestion
      sudo repoquery -y --nvr --show-duplicates st2mistral
```

Because this applies to non-EL8 OS, `yes` flag is no needed here.

Comment (nmaludy) [reply scripts/includes/rhel.sh:31]: was just trying to be consistent here, that way all `repoquery` commands are the same

Comment (nmaludy) [reply scripts/includes/rhel.sh:31]: i would prefer to leave it in, just for consistency, if that's ok?

File: scripts/includes/rhel.sh [hunk 4]
```diff
@@ -9,35 +9,42 @@ install_yum_utils() {
...
       exit 3
     fi
     ST2_PKG=${ST2_VER}
 
-    local RHMAJVER=`cat /etc/redhat-release | sed 's/[^0-9.]*\([0-9.]\).*/\1/'`
-    local ST2MISTRAL_VER=$(repoquery -y --nvr --show-duplicates st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
-    if [ -z "$ST2MISTRAL_VER" && "$RHMAJVER" != '8' ]; then
+    local ST2MISTRAL_VER=$(repoquery ${YES_FLAG} --nvr --show-duplicates st2mistral | grep -F st2mistral-${VERSION} | sort --version-sort | tail -n 1)
+    # RHEL 8 and newer does not install Mistral
+    if [ -z "$ST2MISTRAL_VER" -a "$RHMAJVER" -lt "8" ]; then
```
Comment (armab) [inline scripts/includes/rhel.sh:29]:
```suggestion
    if [ -z "$ST2MISTRAL_VER" && "$RHMAJVER" -lt "8" ]; then
```

Please rely on a more straightforward `&&` which is what we use everywhere. `-a` may lead to confusion, see https://stackoverflow.com/a/321493/4533625

File: scripts/includes/rhel.sh (hunk 3 above)
Comment (armab) [reply scripts/includes/rhel.sh:31]: Sure
